### ISSUE TITLE
Create hash function to generate a shortened URL

### ISSUE THREAD

**Issue by LonnyGomes** [LonnyGomes/urly#4]
This hash function should adhere to the following:

- the hash value should return a constant length
- it can use a-z0-9
- it should avoid the following ambiguous characters
  - 0,O,l,I
- it should be case insensitive

**Comment by panoz7** [comment]
Are you thinking that the hash is completely random or in some way correlated to the URL?

**Comment by LonnyGomes** [comment]
Well, we’ll still need a way to retrieve the original URL yet it it seems like the way other shorteners work is that the input url generates the same output. After thinking about it though, perhaps that isn’t totally necessary.

**Comment by panoz7** [comment]
Just pushed some code with a function that generates a hash. I know it doesn't belong where I put it but I also wasn't sure how you were going to structure everything. We can move it to the correct place later. 

Currently all it does is generate a random string of a certain length out of a certain group of characters. With this approach there is no link between the URL and the hash aside from whatever is stored in the database. Some additional code will be needed to query the database to make sure there isn't a hash collision. This should happen rarely (there's 27 billion possible 7 character hashes that are all lower case and exclude 0, o, 1, and l). 

If we want to match the functionality where the same url always generates the same hash then we would query the db when a user enters a URL to see if a hash has already been generated. If it has we'd return it, otherwise we'd generate a new one. That said, I can see some advantages to generating a unique hash for every submission. For instance, it would allow the submitter to get analytics on who has clicked their specific link, while overall analytics for a specific URL could easily be found by joining all the data from each unique hash. 

Let me know what you think. Happy to approach this from a different direction too if you had something else in mind.

**Comment by LonnyGomes** [comment]
@panoz7 the term I was looking for the other day was [idempotence](https://en.wikipedia.org/wiki/Idempotence). That's just a fancy way of saying that multiple calls to the a function yield the same results.

I took a look at how [TinyURL](https://tinyurl.com/) seems to do things and it does appear that there is a direct mapping from URL->hash in that the same URL will produce the same hash. I somewhat like the idea of the hash function not being dependent on the database, but either way it does seem like we would have to check for collisions. I don't have a strong preference either way yet I would lean to trying to rely on little on a DB as possible. 

I when ahead and moved your code into a `utils/` folder and wrapped it inside of a typescript class. I also added starter unit tests that should be helpful to prototype and test the function. I started a draft PR (#20) where the work could continue.
